import Barchart from '@/components/Barchart'
import Header from '@/components/Header'
import RecentOrders from '@/components/RecentOrders'
import Topcards from '@/components/Topcards'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>VitalMove Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen' >
        <Header/>
        <Topcards/>
       <div className='p-4 grid md:grid-cols-3 gap-4'>
        <Barchart/>
        <RecentOrders/>
        </div> 

      </main>
    </>
  )
}
